name: "CI: Grey"

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: grey

      - name: Workspace tests (interpreter)
        working-directory: grey
        run: cargo +stable test --workspace

      - name: Workspace tests (recompiler)
        working-directory: grey
        run: cargo +stable test --workspace
        env:
          GREY_PVM: recompiler
